-- V1: Criação da tabela 'acao' conforme AcaoEntity
CREATE TABLE acao (
                      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    -- Colunas de texto
                      ticker VARCHAR(10) NOT NULL UNIQUE,
                      nome_empresa VARCHAR(255),
                      setor VARCHAR(100),
                      segmento VARCHAR(100),
                      segmento_listagem VARCHAR(100),
                      disponibilidade VARCHAR(100),

    -- Colunas numéricas
                      preco_atual NUMERIC(15, 4),
                      variacao_12m NUMERIC(10, 2),
                      valor_mercado NUMERIC(25, 2),
                      valor_firma NUMERIC(25, 2),
                      patrimonio_liquido NUMERIC(25, 2),
                      numero_total_papeis NUMERIC(25, 2),
                      ativos NUMERIC(25, 2),
                      ativo_circulantes NUMERIC(25, 2),
                      divida_bruta NUMERIC(25, 2),
                      divida_liquida NUMERIC(25, 2),
                      free_float NUMERIC(10, 4),
                      tag_along NUMERIC(10, 4),
                      liquidez_media_diaria NUMERIC(25, 2),

                      p_l NUMERIC(12, 4),
                      psr NUMERIC(12, 4),
                      p_vp NUMERIC(12, 4),
                      dividend_yield NUMERIC(12, 4),
                      payout NUMERIC(12, 4),
                      margem_liquida NUMERIC(12, 4),
                      margem_bruta NUMERIC(12, 4),
                      margem_ebit NUMERIC(12, 4),
                      margem_ebitda NUMERIC(12, 4),
                      ev_ebitda NUMERIC(12, 4),
                      ev_ebit NUMERIC(12, 4),
                      p_ebitda NUMERIC(12, 4),
                      p_ativo NUMERIC(12, 4),
                      p_capital_de_giro NUMERIC(12, 4),
                      p_ativo_circulante_liquido NUMERIC(12, 4),
                      vpa NUMERIC(12, 4),
                      lpa NUMERIC(12, 4),
                      giro_ativos NUMERIC(12, 4),
                      roe NUMERIC(12, 4),
                      roic NUMERIC(12, 4),
                      roa NUMERIC(12, 4),
                      divida_liquida_patrimonio NUMERIC(12, 4),
                      divida_liquida_ebitda NUMERIC(12, 4),
                      divida_liquida_ebit NUMERIC(12, 4),
                      divida_bruta_patrimonio NUMERIC(12, 4),
                      patrimonio_ativos NUMERIC(12, 4),
                      passivos_ativos NUMERIC(12, 4),
                      liquidez_corrente NUMERIC(12, 4),
                      cagr_receitas_cinco_anos NUMERIC(12, 4),
                      cagr_lucros_cinco_anos NUMERIC(12, 4),

    -- Metadados
                      dados_brutos_json JSONB,
                      data_atualizacao TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Índice de otimização
CREATE INDEX idx_acao_ticker ON acao(ticker);
